export const LOAD_MEDIFUND_FACTORY_CONTRACT =
  "LOAD_CRYPTOBUTE_FACTORY_CONTRACT";
export const GET_HEALTH_BULLETIN_DATA = "GET_HEALTH_BULLETIN_DATA";
export const CREATE_NEW_FUNDRAISER = "CREATE_NEW_FUNDRAISER";
export const GET_FUNDRAISERS = "GET_FUNDRAISERS";
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const USER_SIGNIN = "USER_SIGNIN";
export const USER_SIGNUP = "USER_SIGNUP";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const SIGN_OUT = "SIGN_OUT";
export const GET_PROFILE = "GET_PROFILE";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const SEND_SPENDING_NOTIFICATION = "SEND_SPENDING_NOTIFICATION";
